### ISSUE TITLE
integration test failure: [Errno 20] Not a directory: '/sys/kernel/config/target/iscsi/cpus_allowed_list'

### ISSUE THREAD

**Issue by mbiebl** [storaged-project/udisks#1014]
Version: 2.9.4

When trying to run the integration testsuite on an up-to-date Debian sid VM, I get
```
autopkgtest [16:40:05]: test upstream-system: [-----------------------
/tmp/autopkgtest.nGRgG2/build.nuf/src/src/tests/integration-test:40: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
test_properties (__main__.Drive)
properties of UDisksDrive object ... ok
test_create_fs_unknown_type (__main__.FS)
Format() with unknown type ... ok
test_create_fs_unsupported_label (__main__.FS)
Format() with unsupported label ... ok
test_empty (__main__.FS)
fs: empty ... ok
test_exfat (__main__.FS)
fs: exFAT ... [cli] [ud] ok
test_existing_manual_mount_point (__main__.FS)
fs: does not reuse existing manual mount point ... ok
test_existing_udisks_mount_point (__main__.FS)
fs: reuses existing udisks mount point ... ok
test_ext4 (__main__.FS)
fs: ext4 ... [cli] [ud] Warning: Unable to open /dev/sr1 read-write (Read-only file system).  /dev/sr1 has been opened read-only.
Warning: Unable to open /dev/sr1 read-write (Read-only file system).  /dev/sr1 has been opened read-only.
Warning: Unable to open /dev/sr1 read-write (Read-only file system).  /dev/sr1 has been opened read-only.
Warning: Unable to open /dev/sr1 read-write (Read-only file system).  /dev/sr1 has been opened read-only.
ok
test_force_removal (__main__.FS)
fs: forced removal ... ok
test_zero (__main__.FS)
properties of zeroed out device ... ok
Warning: The resulting partition is not properly aligned for best performance: 34s % 2048s != 0s
test_devname (__main__.Fstab)
by device name ... ok
test_label (__main__.Fstab)
by label ... ok
test_partlabel (__main__.Fstab)
by PARTLABEL ... ok
test_partuuid (__main__.Fstab)
by PARTUUID ... ok
test_uuid (__main__.Fstab)
by UUID ... ok
test_0_create_teardown (__main__.Luks)
LUKS create/teardown ... ok
test_ascii_keyfile_newline (__main__.Luks) ... [cleanup lock] ok
test_binary_keyfile (__main__.Luks) ... ok
test_change_passphrase (__main__.Luks) ... ok
test_keyfile_equivalent (__main__.Luks)
Setup device using passphrase, unlock using keyfile. ... ok
test_luks_forced_removal (__main__.Luks)
LUKS forced removal ... ok
test_luks_mount (__main__.Luks)
LUKS mount/unmount ... ok
test_plaintext_keyfile (__main__.Luks)
Setup a device using a plaintext keyfile. ... ok
Warning: Could not load preferences file /root/.targetcli/prefs.bin.
Configuration restored from /tmp/autopkgtest.nGRgG2/build.nuf/src/src/tests/dbus-tests/targetcli_config.json
test_md_raid_methods (__main__.MDRaid) ... mdadm: array /dev/md/int_test0 started.
mdadm: stopped /dev/md/int_test0
ok
[Errno 20] Not a directory: '/sys/kernel/config/target/iscsi/cpus_allowed_list'
ERROR
test_loop_ro (__main__.Manager)
loop device R/O ... ok
test_loop_rw (__main__.Manager)
loop device R/W ... ok
test_version (__main__.Manager)
daemon version ... ok
test_internal_fs_allowed (__main__.Polkit)
Create FS on internal drive (allowed) ... ok
test_internal_fs_forbidden (__main__.Polkit)
Create FS on internal drive (forbidden) ... ok
test_removable_fs (__main__.Polkit)
Mount FS on removable drive (allowed) ... ok
test_sda (__main__.Smart)
SMART status of first internal hard disk ... Failed to query whether SMART is available: Operation not supported
[N/A] ok

======================================================================
ERROR: tearDownClass (__main__.MDRaid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.nGRgG2/build.nuf/src/src/tests/integration-test", line 1873, in tearDownClass
    remove_lio()
  File "/tmp/autopkgtest.nGRgG2/build.nuf/src/src/tests/integration-test", line 1799, in remove_lio
    assert subprocess.call(['targetcli', 'clearconfig confirm=True']) == 0
AssertionError

----------------------------------------------------------------------
Ran 31 tests in 316.917s
```

This apparently only seems to happen with newer kernels. The Debian VM has 5.18.x

Looking a bit more closely, the error is caused by `remove_lio()`, specifically 
```
# targetcli clearconfig confirm=True
[Errno 20] Not a directory: '/sys/kernel/config/target/iscsi/cpus_allowed_list'
# echo $?
1

# apt-cache policy targetcli-fb
targetcli-fb:
  Installed: 1:2.1.53-1
  Candidate: 1:2.1.53-1
  Version table:
 *** 1:2.1.53-1 500
        500 http://deb.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by vojtechtrefny** [comment]
You need the latest version of rtslib-fb, see https://github.com/open-iscsi/rtslib-fb/pull/183 Looks like 2.1.75 is available only in experimental.

**Comment by mbiebl** [comment]
Confirmed. With 2.1.75 the testsuite passes. Thanks a lot for the reference to the relevant issue.
