### ISSUE TITLE
test suite failure:  cls.devices = setup_lio()

### ISSUE THREAD

**Issue by mbiebl** [storaged-project/udisks#1238]
Running the test suite on Debian sid yields

```
SMART status of first internal hard disk ... Failed to query whether SMART is available: Operation not supported
[N/A] ok

======================================================================
ERROR: setUpClass (__main__.MDRaid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.2VZF5S/build.ytB/src/src/tests/integration-test", line 1871, in setUpClass
    cls.devices = setup_lio()
                  ^^^^^^^^^^^
  File "/tmp/autopkgtest.2VZF5S/build.ytB/src/src/tests/integration-test", line 1780, in setup_lio
    assert subprocess.call(
           ^^^^^^^^^^^^^^^^
AssertionError

----------------------------------------------------------------------
Ran 30 tests in 322.252s

```

**Comment by tbzatek** [comment]
I think there should be another message from `targetcli` somewhere. Is this related to a new kernel version? Do you have #1210 applied?
