### ISSUE TITLE
FAIL: test_ext4: fsconfig system call failed: /dev/sr1: Can't open blockdev

### ISSUE THREAD

**Issue by mbiebl** [storaged-project/udisks#1273]
Version: 2.10.1 / HEAD
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1070019

Running the upstream test suite (via autopkgtest) triggers this failure in Debian sid:
```
======================================================================
FAIL: test_ext4 (__main__.FS.test_ext4)
fs: ext4
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.tgUSRL/build.qT8/src/src/tests/integration-test", line 1107, in _do_udisks_check
    cd_fs.call_mount_sync(ro_options, None)
gi.repository.GLib.GError: udisks-error-quark: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error mounting /dev/sr1 at /media/root/6e9fdd2f-90ee-4b54-b0d1-28b25e652896: fsconfig system call failed: /dev/sr1: Can't open blockdev (0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/autopkgtest.tgUSRL/build.qT8/src/src/tests/integration-test", line 725, in test_ext4
    self._do_fs_check('ext4')
  File "/tmp/autopkgtest.tgUSRL/build.qT8/src/src/tests/integration-test", line 894, in _do_fs_check
    self._do_udisks_check(fs_type)
  File "/tmp/autopkgtest.tgUSRL/build.qT8/src/src/tests/integration-test", line 1112, in _do_udisks_check
    self.fail('Mounting read-only device with \'rw\' option failed'
AssertionError: Mounting read-only device with 'rw' option failedwith an unexpected error.
Got: udisks-error-quark: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error mounting /dev/sr1 at /media/root/6e9fdd2f-90ee-4b54-b0d1-28b25e652896: fsconfig system call failed: /dev/sr1: Can't open blockdev (0)
Expected: 'is write-protected but explicit read-write mode requested' or 'is write-protected but `rw' option given'

----------------------------------------------------------------------
Ran 31 tests in 292.422s

FAILED (failures=1)
```
This is with util-linux 2.40

Full test log is available at https://ci.debian.net/packages/u/udisks2/testing/amd64/46012968/

**Comment by zeha** [comment]
Seems likely that https://github.com/util-linux/util-linux/commit/9da5644e414cdc318f0311260dabc6035c85b58e causes this. u-l now passes through the kernel's error message.

**Comment by tbzatek** [comment]
> Seems likely that [util-linux/util-linux@9da5644](https://github.com/util-linux/util-linux/commit/9da5644e414cdc318f0311260dabc6035c85b58e) causes this. u-l now passes through the kernel's error message.

Thanks, that explains it. Not so nice message though.

**Comment by zeha** [comment]
> Not so nice message though.

yes :(
