### ISSUE TITLE
Error occurs on the execution of /dbus-tests/run_test.py

### ISSUE THREAD

**Issue by xhe123** [storaged-project/udisks#405]
```
root@nndesktop1# (git::origin) python run_tests.py 
Restore file src/tests/dbus-tests/targetcli_config.json not found
Coping file: /var/nn/udisks/data/org.freedesktop.UDisks2.policy to /usr/share/polkit-1/actions/ directory!
Coping file: /var/nn/udisks/modules/iscsi/data/org.freedesktop.UDisks2.iscsi.policy to /usr/share/polkit-1/actions/ directory!
Coping file: /var/nn/udisks/modules/zram/data/org.freedesktop.UDisks2.zram.policy to /usr/share/polkit-1/actions/ directory!
Coping file: /var/nn/udisks/modules/btrfs/data/org.freedesktop.UDisks2.btrfs.policy to /usr/share/polkit-1/actions/ directory!
Coping file: /var/nn/udisks/modules/bcache/data/org.freedesktop.UDisks2.bcache.policy to /usr/share/polkit-1/actions/ directory!
Coping file: /var/nn/udisks/modules/lsm/data/org.freedesktop.UDisks2.lsm.policy to /usr/share/polkit-1/actions/ directory!
Coping file: /var/nn/udisks/modules/lvm2/data/org.freedesktop.UDisks2.lvm2.policy to /usr/share/polkit-1/actions/ directory!
Coping file: /var/nn/udisks/data/org.freedesktop.UDisks2.conf to /etc/dbus-1/system.d/ directory!
Coping file: /var/nn/udisks/data/80-udisks2.rules to /usr/lib/udev/rules.d/ directory!
udisks-Message: udisks daemon version 2.7.2 starting

(lt-udisksd:24384): udisks-WARNING **: Can't load configuration file /var/nn/udisks/udisks2/udisks2.conf
udisks-Message: Acquired the name org.freedesktop.UDisks2 on the system message bus
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR
test_btrfs (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: setUpClass (test_40_drive.UdisksDriveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/nn/udisks/src/tests/dbus-tests/udiskstestcase.py", line 186, in setUpClass
    assert len(self.vdevs) > 3;
AssertionError

======================================================================
ERROR: setUpClass (test_loop.UdisksLoopDeviceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/nn/udisks/src/tests/dbus-tests/udiskstestcase.py", line 186, in setUpClass
    assert len(self.vdevs) > 3;
AssertionError

======================================================================
ERROR: setUpClass (test_loop.UdisksManagerLoopDeviceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/nn/udisks/src/tests/dbus-tests/udiskstestcase.py", line 175, in setUpClass
    sys_info = self.bus.get_object("org.freedesktop.hostname1", "/org/freedesktop/hostname1")
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/var/nn/udisks/src/tests/dbus-tests/udiskstestcase.py", line 13, in call_long
    return call(*args, **kwargs)
TypeError: unbound method call_long() must be called with UdisksLoopDeviceTest instance as first argument (got str instance instead)

======================================================================
ERROR: setUpClass (test_50_block.UdisksBlockTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/nn/udisks/src/tests/dbus-tests/udiskstestcase.py", line 175, in setUpClass
    sys_info = self.bus.get_object("org.freedesktop.hostname1", "/org/freedesktop/hostname1")
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/var/nn/udisks/src/tests/dbus-tests/udiskstestcase.py", line 13, in call_long
    return call(*args, **kwargs)
TypeError: unbound method call_long() must be called with UdisksLoopDeviceTest instance as first argument (got str instance instead)
```
...

For more details of this error log http://pastebin.test.redhat.com/515633

**Comment by vpodzime** [comment]
The tests are expected to be run with ``make dbus-tests`` or, ideally, ``make ci``. The README.md file mentions that.
