### ISSUE TITLE
run_test.py - FileNotFoundError: [Errno 2] No such file or directory: 'udisksctl'

### ISSUE THREAD

**Issue by xhe123** [storaged-project/udisks#410]
Hit this Error during the run_tests.py, it always raise error, but the 'udisksctl' command works well.

`Traceback (most recent call last):
  File "src/tests/dbus-tests/run_tests.py", line 233, in <module>
    result = unittest.TextTestRunner(verbosity=2).run(suite)
  File "/usr/lib64/python3.6/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/lib64/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib64/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib64/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib64/python3.6/unittest/case.py", line 670, in __call__
    return self.run(*args, **kwds)
  File "/root/udisks/src/tests/dbus-tests/udiskstestcase.py", line 227, in run
    with CmdFlightRecorder("udisksctl monitor", ["udisksctl", "monitor"], record):
  File "/root/udisks/src/tests/dbus-tests/udiskstestcase.py", line 377, in __enter__
    self._start()
  File "/root/udisks/src/tests/dbus-tests/udiskstestcase.py", line 404, in _start
    self._proc = subprocess.Popen(self._argv, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'udisksctl'
make: *** [Makefile:938: dbus-tests] Error 1

$ udisksctl  -h
Unknown command `-h'
Usage:
  udisksctl COMMAND
Commands:
  help            Shows this information
  info            Shows information about an object
  dump            Shows information about all objects
  status          Shows high-level status
  monitor         Monitor changes to objects
  mount           Mount a filesystem
  unmount         Unmount a filesystem
  unlock          Unlock an encrypted device
  lock            Lock an encrypted device
  loop-setup      Set-up a loop device
  loop-delete     Delete a loop device
  power-off       Safely power off a drive
  smart-simulate  Set SMART data for a drive

Use "udisksctl COMMAND --help" to get help on each command.

`

**Comment by vpodzime** [comment]
Do you have the ``$PATH`` variable setup properly for the *root* user? What if you try ``sudo udisksctl``?

**Comment by xhe123** [comment]
Oh , it shows command not found with sudo.
# sudo udisksctl
sudo: udisksctl: command not found
# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

**Comment by xhe123** [comment]
I prepared one test server for this issue, please feel free to login and check anything. 
10.66.12.169 (root/123456)

**Comment by vpodzime** [comment]
This is an effect of the *sudo* configuration being used.
