### ISSUE TITLE
ext4 test often fails on call_mount_sync call

### ISSUE THREAD

**Issue by seb128** [storaged-project/udisks#513]
Since Ubuntu update udisks from 2.6 to 2.7.6 our integration test are often hitting that error

"======================================================================
ERROR: test_ext4 (__main__.FS)
fs: ext4
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/integration-test", line 680, in test_ext4
    self._do_fs_check('ext4')
  File "src/tests/integration-test", line 841, in _do_fs_check
    self._do_udisks_check(fs_type)
  File "src/tests/integration-test", line 1045, in _do_udisks_check
    cd_fs.call_mount_sync(ro_options, None)
AttributeError: 'NoneType' object has no attribute 'call_mount_sync'"

(the full test log is on https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic/bionic/arm64/u/udisks2/20180316_130137_263ea@/log.gz)

**Comment by seb128** [comment]
bah, it looks like that was what the delay added in bug #ce5ed705 is resolving
