### ISSUE TITLE
FS.test_exfat integration-test failure

### ISSUE THREAD

**Issue by mbiebl** [storaged-project/udisks#680]
Version: 2.8.3

Trying to run `src/tests/integration-test FS.test_exfat` I get the following failure:
```
# src/tests/integration-test FS.test_exfat
Testing installed system binaries
daemon path: /usr/lib/udisks2/udisksd
Set up test device: r/w: /dev/sda, r/o: /dev/sr1
test_exfat (__main__.FS)
fs: exFAT ... [cli] FUSE exfat 1.3.0
FUSE exfat 1.3.0
WARN: volume was not unmounted cleanly.
FUSE exfat 1.3.0
FUSE exfat 1.3.0
WARN: volume was not unmounted cleanly.
[ud] FAIL

======================================================================
FAIL: test_exfat (__main__.FS)
fs: exFAT
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/integration-test", line 694, in test_exfat
    self._do_fs_check('exfat')
  File "src/tests/integration-test", line 859, in _do_fs_check
    self._do_udisks_check(fs_type)
  File "src/tests/integration-test", line 1074, in _do_udisks_check
    self.fail('Mounting read-only device didn\'t fail with \'rw\' option.')
AssertionError: Mounting read-only device didn't fail with 'rw' option.

----------------------------------------------------------------------
Ran 1 test in 49.258s

FAILED (failures=1)
```
```
# apt-cache policy exfat-fuse exfat-utils
exfat-fuse:
  Installed: 1.3.0-1
  Candidate: 1.3.0-1
  Version table:
 *** 1.3.0-1 500
        500 http://deb.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
exfat-utils:
  Installed: 1.3.0-1
  Candidate: 1.3.0-1
  Version table:
 *** 1.3.0-1 500
        500 http://deb.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```

Test system is Debian sid.

**Comment by vojtechtrefny** [comment]
Tested this with both Debian and Fedora and mounting an exFAT filesystem on a read-only device using the `rw` option doesn't result in an error like other filesystems. I guess exFAT is just another exception.

```
$ sudo mount /dev/vde1 /mnt/test -o rw
FUSE exfat 1.3.0
WARN: '/dev/vde1' is write-protected, mounting read-only.
```
